#!/bin/sh

VER=1.2.1
if [ -x /usr/bin/fagodb-create-db.sh ]; then
  echo "executing /usr/bin/fagodb-create-db.sh"
  /usr/bin/fagodb-create-db.sh
else
  echo "couldnt find /usr/bin/fagodb-create-db.sh or is not executable"
fi

CONFWEB='/usr/share/Fago-DBFW/config.php'
if test -f $CONFWEB
then
  cp -a $CONFWEB ${CONFWEB}-old
else
  if [ -f /usr/share/doc/Fago-DBFW-$VER/config.php ]; then
    cp "/usr/share/doc/Fago-DBFW-$VER/config.php" $CONFWEB
  elif  [ -f /usr/share/doc/Fago-DBFW/config.php ]; then
    cp "/usr/share/doc/Fago-DBFW/config.php" $CONFWEB
  fi
fi

